- name: Detect install-scripts 
  shell: which pacstrap && which genfstab && which arch-chroot
  register: install_scripts_installed
  ignore_errors: yes
  changed_when: False

- name: Detect pacman
  shell: pacman -V | grep libalpm
  register: pacman_installed
  ignore_errors: yes
  changed_when: False

- name: Detect reflector
  shell: which reflector
  register: reflector_installed
  ignore_errors: yes
  changed_when: False

- set_fact:
    pacstrap: pacstrap
    genfstab: genfstab
    chroot: "arch-chroot {{ mount_dir }}"
    pacman_prefix: /
