- block:
  - name: Try to install reflector via package manager
    package: name=reflector state=present
  rescue:
  - name: Install build tools
    package: name={{ item }} state=present
    with_items:
      - python3

  - set_fact:
      reflector_dir: "{{ temp_dir }}/{{ reflector_version }}"

  - name: Get reflector
    shell: curl https://xyne.archlinux.ca/projects/reflector/src/{{ reflector_version }}.tar.xz | tar -C {{ temp_dir }} -x --xz
  when: reflector_required
