- name: Install base system
  command: "{{ pacstrap }} -cM -C {{ pacman_prefix }}/etc/pacman.conf {{ mount_dir }} base openssh python"
  args:
    creates: "{{ mount_dir }}/etc/arch-release"
  environment:
    PATH: "{{ pacman_prefix }}/bin:{{ ansible_env.PATH }}"

- name: Copy mirrorlist
  command: cp -a {{ pacman_prefix }}/etc/pacman.d/mirrorlist {{ mount_dir }}/etc/pacman.d/mirrorlist

- name: Fix ca certificates
  command: "{{ chroot }} update-ca-trust"
