- name: Check if special chroot is necessary
  stat: path={{ mount_dir }}/dev/zero
  register: dev_zero
- set_fact:
    chroot: "{{ mount_dir }}/usr/bin/arch-chroot {{ mount_dir }}"
  when: chroot is not defined
- set_fact:
    chroot: "chroot {{ mount_dir }}"
  when: dev_zero.stat.exists

- set_fact:
    pacman: "{{ chroot }} pacman --noconfirm"

- name: Initialize pacman keys
  command: "{{ chroot }} pacman-key --init"
  args:
    creates: "{{ mount_dir }}/etc/pacman.d/gnupg"

- name: Update pacman keys
  command: "{{ chroot }} pacman-key --populate archlinux"

- name: Update packages
  command: "{{ pacman }} -Syu"

- name: Install optional packages
  command: "{{ pacman }} -S {{ extra_packages | join(' ') }}"
  when: extra_packages is defined and (extra_packages | length) > 0
