- block:
  - name: Check for existing fstab
    command: grep -q '^\w*[^#]' {{ mount_dir }}/etc/fstab
    changed_when: False
  rescue:
  - name: Generate fstab
    shell: "{{ genfstab }} -U {{ mount_dir }} > {{ mount_dir }}/etc/fstab"
