- name: Generate fstab
  shell: "{{ genfstab }} -U {{ mount_dir }} > {{ mount_dir }}/etc/fstab"
  args:
    creates: "{{ mount_dir }}/etc/fstab"

- name: Update mirrors
  command: "reflector --protocol https --age 1 --number 10 --sort rate"
  when: base_installation.changed

- name: Update packages
  command: "{{ chroot }} pacman -Sy"

- name: Install additional packages
  command: "{{ chroot }} pacman -S {{ extra_packages | join(' ') }}"
