- name: Install systemd-boot
  command: "{{ chroot }} bootctl --path=/boot install"
  args:
    creates: "{{ mount_dir }}/boot/EFI/systemd"
  register: systemd_fresh_install

- name: Remove default loader.conf
  file: path="{{ mount_dir }}/boot/loader/loader.conf" state=absent
  when: systemd_fresh_install.changed

- name: Get root drive UUID
  shell: blkid {{ root_device }} | grep -oP ' UUID="\K[^"]+'
  register: root_blkid
  changed_when: False

- name: Get boot drive UUID
  shell: blkid {{ boot_device }} | grep -oP ' UUID="\K[^"]+'
  register: boot_blkid
  changed_when: False

- set_fact:
    root_uuid: "{{ root_blkid.stdout }}"
    boot_uuid: "{{ boot_blkid.stdout }}"
    cpu_vendor: "{{ 'intel' if 'GenuineIntel' in ansible_facts.processor else 'amd' }}"

- name: Install microcode
  command: "{{ pacman }} -S {{ cpu_vendor }}-ucode"
  args:
    creates: "{{ mount_dir }}/boot/{{ cpu_vendor }}-ucode.img"

- name: Configure bootloader
  copy:
    src: loader.conf
    dest: "{{ mount_dir }}/boot/loader/loader.conf"
    force: no

- name: Configure bootloader
  template:
    src: arch.conf
    dest: "{{ mount_dir }}/boot/loader/entries/arch.conf"
    force: no
