---
- block:
  - name: Create new filesystem
    include: 00-create-filesystem.yml
    when: format_device is defined

  - name: Mount the filesystem
    include: 10-mount-filesystem.yml
    when: root_device is defined and boot_device is defined

  - name: Check dependencies
    include: 30-check-dependencies.yml

  - name: Install dependency install-scripts
    include: 31-install-scripts.yml

  - name: Install dependency pacman
    include: ./32-install-pacman.yml

  - name: Install dependency reflector
    include: ./33-install-reflector.yml

  - name: Install base system
    include: 40-install-base.yml
    when: base_install_required

  - name: Install extra packages
    include: 41-install-extra.yml

  - name: Provide basic configuration
    include: 50-configure-essential.yml

  - name: Provide optional configuration
    include: 51-configure-optional.yml

  - name: Install bootloader
    include: 70-install-bootloader.yml

  - name: Provide additional configuration
    include: 75-configure-extra.yml

  - name: Report new UUIDs
    include: 80-report.yml

  - name: Reboot
    include: 90-reboot.yml
  rescue:
  - name: Reboot
    include: 99-cleanup.yml
  become: true
  become_user: root
