---
- block:
  - name: Create new filesystem
    include: 00-create-filesystem.yml
    when: format_device is defined

  - name: "All required variables set"
    assert: 
      fail_msg: "Vars `format_device` or [`root_device` and `boot_device`] are required to be set"
      that: 
        - root_device is defined
        - boot_device is defined

  - name: Mount the filesystem
    include: 10-mount-filesystem.yml

  - name: Check if Arch is already installed
    stat: path={{ mount_dir }}/etc/arch-release
    register: arch_installed

  - block:
    - name: Install dependencies
      include: 30-check-dependencies.yml

    - name: Install dependency install-scripts
      include: 31-install-scripts.yml

    - name: Install dependency pacman
      include: ./32-install-pacman.yml

    - name: Install dependency reflector
      include: ./33-install-reflector.yml

    - name: Install base system
      include: 40-install-base.yml
    when: not arch_installed.stat.exists

  - name: Provide basic configuration
    include: 50-configure.yml

  - name: Install bootloader
    include: 70-install-bootloader.yml

  - name: Cleanup
    include: 90-cleanup.yml
  become: true
  become_user: root
